sudo dscl . -delete /Groups/netaccounts
sudo dscl . -delete /Groups/netusers
sudo dscl . -delete /Groups/network
sudo dscl . -delete /Groups/_biom
sudo dscl . -delete /Groups/_appowner
sudo dscl . -delete /Groups/_appserverusr
sudo dscl . -delete /Groups/_ard
sudo dscl . -delete /Groups/_assetcache
sudo dscl . -delete /Groups/_cvs
sudo dscl . -delete /Groups/_ctkd
sudo dscl . -delete /Groups/_notification_proxy
sudo dscl . -delete /Groups/_displaypolicyd
sudo dscl . -delete /Groups/_locationd
sudo dscl . -delete /Groups/_distnote
sudo dscl . -delete /Groups/_gamecontrollerd
sudo dscl . -delete /Groups/_eppc
sudo dscl . -delete /Groups/_eligabilityd
sudo dscl . -delete /Groups/_diagnosticservicesd
sudo dscl . -delete /Groups/_diskimagesiod
sudo dscl . -delete /Groups/_mobilegestalthelper
sudo dscl . -delete /Groups/_modelmanagerd
sudo dscl . -delete /Groups/_postfix
sudo dscl . -delete /Groups/_eligibilityd
sudo dscl . -delete /Groups/_detachedsig
sudo dscl . -delete /Groups/_developer
sudo dscl . -delete /Groups/_accessoryupdater
sudo dscl . -delete /Groups/_eligibilityd
sudo dscl . -delete /Groups/_atsserver
sudo dscl . -delete /Groups/_cmiodalassistants
sudo dscl . -delete /Groups/_detachedsig
sudo dscl . -delete /Groups/_amavisd
sudo dscl . -delete /Groups/_appowner
sudo dscl . -delete /Groups/_appserverusr
sudo dscl . -delete /Groups/_aonsensed
sudo dscl . -delete /Groups/_keytabuser
sudo dscl . -delete /Groups/_analyticsusers
sudo dscl . -delete /Groups/_appleevents
sudo dscl . -delete /Groups/_applepay
sudo dscl . -delete /Groups/_appstore
sudo dscl . -delete /Groups/_astris
sudo dscl . -delete /Groups/_backgroundassets
sudo dscl . -delete /Groups/_biome
sudo dscl . -delete /Groups/_calendar
sudo dscl . -delete /Groups/_hidds
sudo dscl . -delete /Groups/com.apple.access_sessionkey
sudo dscl . -delete /Groups/_reportmemoryexception
sudo dscl . -delete /Groups/_devdocs
sudo dscl . -delete /Groups/_iconservices
sudo dscl . -delete /Groups/_neuralengine
sudo dscl . -delete /Groups/_taskgated
sudo dscl . -delete /Groups/_devicemgr
sudo dscl . -delete /Groups/_datadetectors

